title: Portfolio # your name (or website title) here
logo: "/img/profil.jpg?raw=true" <!-- width="20" height="20" --> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am a fresh graduate from Universitas Airlangga, holding a degree in Information Systems.
  I am a data-driven individual with a strong eagerness to acquire new skills. My focus lies in the data-related field. 
  <br><br>
  <a href="https://www.linkedin.com/in/ardina-dana-nugraha-03a47b249/">LinkedIn</a>
  <br><br>
  <a href="https://github.com/ardinadnn/">LinkedIn</a>

remote_theme: yaoyao-liu/minimal

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

auto_dark_mode: true
#show_downloads: true
